### ISSUE TITLE
Investigate - Dynamics ERP

### ISSUE THREAD

**Issue by jefim** [FrendsPlatform/FrendsTasks#25]
Target: create new tasks for Dynamics ERP that are built according to our new task building practices.

Todo:
- Review the current task implementation if any
- Utilize OData or their native libraries
- Maybe look into using OData as generic way to query?
- Other tasks?
- Check how we can get a test instance and what it would cost us. E.g. spin up something in cloud for some price.

**Comment by ttossavainen** [comment]
https://github.com/FrendsPlatform/Frends.MicrosoftDynamics/issues/1
